// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-O6-VoURCw3PDRHgnh6_X4E03yj_wWxQ',
    appId: '1:853476451490:web:def2c2da8da4fb4e17e3fb',
    messagingSenderId: '853476451490',
    projectId: 'sunu-projet-26a78',
    authDomain: 'sunu-projet-26a78.firebaseapp.com',
    storageBucket: 'sunu-projet-26a78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnq2sU8HtExbJoeo5qhvn7PJgIgMQYZPo',
    appId: '1:853476451490:android:0b695598339d375717e3fb',
    messagingSenderId: '853476451490',
    projectId: 'sunu-projet-26a78',
    storageBucket: 'sunu-projet-26a78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANUmIOxb0LJkKVC3K6ewjSe-u-xxEFkQo',
    appId: '1:853476451490:ios:641eda9a4c08580217e3fb',
    messagingSenderId: '853476451490',
    projectId: 'sunu-projet-26a78',
    storageBucket: 'sunu-projet-26a78.firebasestorage.app',
    iosBundleId: 'com.domain.sunuProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANUmIOxb0LJkKVC3K6ewjSe-u-xxEFkQo',
    appId: '1:853476451490:ios:641eda9a4c08580217e3fb',
    messagingSenderId: '853476451490',
    projectId: 'sunu-projet-26a78',
    storageBucket: 'sunu-projet-26a78.firebasestorage.app',
    iosBundleId: 'com.domain.sunuProjet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-O6-VoURCw3PDRHgnh6_X4E03yj_wWxQ',
    appId: '1:853476451490:web:a7f0981b1f1540cb17e3fb',
    messagingSenderId: '853476451490',
    projectId: 'sunu-projet-26a78',
    authDomain: 'sunu-projet-26a78.firebaseapp.com',
    storageBucket: 'sunu-projet-26a78.firebasestorage.app',
  );
}
